# {build} is required by AppVeyor to uniquely identify its builds on the url
# It is a continuously incrementing number so when used it violates the reset
# smaller build parts rule of semantic versioning. Therefore we introduce a
# second environment variable semantic_version.
version: 0.5.0.{build}

configuration:
  - Debug
  - Release

install:
  - cmd: set semantic_version=%APPVEYOR_BUILD_VERSION:~0,5%
  - cmd: echo %semantic_version%
  - cmd: set truncated_repo_commit=%APPVEYOR_REPO_COMMIT:~0,10%
  - cmd: echo %truncated_repo_commit%
  - nuget restore

nuget:
  disable_publish_on_pr: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(semantic_version).{build}'
  assembly_file_version: '$(semantic_version).{build}'
  assembly_informational_version: '$(semantic_version)-$(truncated_repo_commit)'

build:
  publish_nuget: true
  parallel: true
  verbosity: normal