version: 0.5.0.{build}

configuration:
  - Debug
  - Release

install:
  - cmd: set TRUNCATED_REPO_COMMIT=%APPVEYOR_REPO_COMMIT:~0,6%
  - nuget restore

nuget:
  disable_publish_on_pr: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(TRUNCATED_REPO_COMMIT)'

build:
  publish_nuget: true
  parallel: true
  verbosity: normal